Reserva_de_gas/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from Reserva_de_gas import settings
from apps.balita.views.index.views import Startpage
from apps.balita.views.contrato.views import *
from apps.balita.views.incidencia.views import *
from apps.balita.views.reserva.views import *
from apps.balita.views.venta.views import *

urlpatterns = \
    [
        path('admin/', admin.site.urls),
        path('api-auth/', include('rest_framework.urls')),
        path('', include('apps.balita.urls')),
        path('', include('apps.user.urls')),
        path('', Startpage.as_view(), name='index'),
        path('login/', include('apps.login.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/balita/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from apps.balita.views.contrato.views import *
from apps.balita.views.incidencia.views import *
from apps.balita.views.reserva.views import *
from apps.balita.views.venta.views import *

# from apps.balita.views.index.views import cerrar_sesion

app_name = 'balita'

urlpatterns = [
    # auth
    # path('logout/', cerrar_sesion, name='cerrar_sesion'),
    # Contrato
    path('contrato/list/', ContratoListView.as_view(), name='contrato_list'),
    path('contrato/add/', ContratoCreateView.as_view(), name='contrato_add'),
    path('contrato/update/<int:pk>/', ContratoUpdateView.as_view(), name='contrato_update'),
    path('contrato/delete/<int:pk>/', ContratoDeleteView.as_view(), name='contrato_delete'),
    # Incidencias
    path('incidencia/list/', IncidenciaListView.as_view(), name='incidencia_list'),
    path('incidencia/add/', IncidenciaCreateView.as_view(), name='incidencia_add'),
    path('incidencia/update/<int:pk>/', IncidenciaUpdateView.as_view(), name='incidencia_update'),
    path('incidencia/delete/<int:pk>/', IncidenciaDeleteView.as_view(), name='incidencia_delete'),
    # Reservas
    path('reserva/list/', ReservaListView.as_view(), name='reserva_list'),
    path('reserva/add/', ReservaCreateView.as_view(), name='reserva_add'),
    path('reserva/update/<int:pk>/', ReservaUpdateView.as_view(), name='reserva_update'),
    path('reserva/delete/<int:pk>/', ReservaDeleteView.as_view(), name='reserva_delete'),
    # Ventas
    path('venta/list/', VentaListView.as_view(), name='venta_list'),
    path('venta/add/', VentaCreateView.as_view(), name='venta_add'),
    path('venta/update/<int:pk>/', VentaUpdateView.as_view(), name='venta_update'),
    path('venta/delete/<int:pk>/', VentaDeleteView.as_view(), name='venta_delete'),
]

apps/login/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from apps.login.views import LoginFormView

urlpatterns = [
    path('', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

apps/user/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from apps.user.views import *

app_name = 'user'

router = DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('user/list/', UserListView.as_view(), name='user_list'),
    path('user/add/', UserCreateView.as_view(), name='user_add'),
    path('user/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('user/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('api/', include(router.urls)),
]

apps/login/models.py
from django.db import models

# Create your models here.

apps/login/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.views.generic import RedirectView

import Reserva_de_gas.settings as setting


# Create your views here.
class LoginFormView(LoginView):
    template_name = 'login/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(setting.LOGIN_REDIRECT_URL)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Login'
        return context


class LogoutRedirectView(RedirectView):
    pattern_name = 'login'

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return super().dispatch(request, *args, **kwargs)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ title }}</title>

    <link rel="icon" href="{% static 'img/balita2.png' %}" type="image/x-icon">
    <!-- Material icons -->
    <link rel="stylesheet" href="{% static 'lib/material-icons/css/icons.min.css' %}">
    <!-- jQuery -->
    <script src="{% static 'lib/jquery/jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'lib/bootstrap-4.6.0-dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/admin-lte3/css/adminlte.min.css' %}">
    <!-- AdminLTE App -->
    <script src="{% static 'lib/admin-lte3/js/adminlte.min.js' %}"></script>
    <!-- sweetAlert -->
    <link rel="stylesheet" href="{% static 'lib/sweetalert2/sweetalert2.min.css' %}">
    <script src="{% static 'lib/sweetalert2/sweetalert2.all.min.js' %}"></script>
    <!-- jquery-confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- Functions -->
    <script src="{% static 'js/function.js' %}"></script>
    <!-- My css -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <!-- Block head -->
    {% block head %}

    {% endblock %}
</head>
{% block body %}

{% endblock %}
</html>

templates/base_list.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% load static %}
{% block head %}

    {% comment %}    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap.min.css' %}">
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/css/buttons.bootstrap4.min.css' %}">
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/buttons.colVis.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/pdfmake-0.1.36/pdfmake.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/pdfmake-0.1.36/vfs_fonts.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/jszip-2.5.0/jszip.min.js' %}"></script>{% endcomment %}

    {% block head_list %}

    {% endblock %}
{% endblock %}

{% block content %}

    <div class="card card-info circular m-0">
        <div class="card-header circular-top">
            <h3 class="card-title">
                <i class="mdi mdi-format-list-bulleted-square mdi-18px"></i>
                {{ title }}
            </h3>
            {% block search %}
                {% comment %}                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input id="searchInput" oninput="w3.filterHTML('#listTable', ['.odd', '.even'], this.value)"
                               type="text"
                               name="table_search"
                               class="form-control float-right"
                               placeholder="Search">

                    </div>
                </div>{% endcomment %}
            {% endblock %}
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-2" style="min-height: 325px;">
            <table id="listTable" class="table  table-striped w3-hoverable-light">
                <thead>
                {% block columns %}

                {% endblock %}

                </thead>
                <tbody id="tbody">

                {% block rows %}

                {% endblock %}

                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
        {% block buttons_list %}
            <div class="card-footer circular-bottom">
                <a href="{{ create_url }}" class="btn btn-primary btnAdd circular">
                    <i class="mdi mdi-plus"></i> Nuevo {{ entity }}
                </a>
            </div>
        {% endblock %}

    </div>
    <!-- /.card -->
    {% block modal_form %}
        <!-- Modal Create_Update -->
        {#        {% include 'modal.html' %}#}
    {% endblock %}


{% endblock %}

{% block javascript %}

{% endblock %}

templates/body.html
{% extends 'base.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Sidebar -->
        {% include 'sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            {% block content_header %}
                <div class="content-header py-2">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1 class="m-0 text-dark pl-lg-5"> Bienvenido
                                    <small>{% if request.user.get_full_name %}{{ request.user.get_full_name }}{% else %}
                                        {{ request.user.username }}{% endif %}</small></h1>
                            </div>
                            <div class="col-sm-6">
                                <ol class="breadcrumb float-sm-right pr-lg-5">
                                    <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
                                    <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock %}
            <div class="content px-0">
                <div class="container-fluid px-lg-5">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
      {% if messages %}
        let html = `<p>`;
        {% for message in messages %}
          html += `{{ message }}<br>`;
        {% endfor %}
        html += `</p>`;
        Swal.fire({
          title: 'Error',
          html: html,
          icon: 'error'
        });
      {% endif %}
    </script>
    </body>
{% endblock %}

templates/delete.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-default circular-top circular-bottom">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="mdi mdi-trash-can-outline"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body circular-bottom">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                        <h5><i class="icon mdi mdi-alert-decagram-outline"></i>Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="alert alert-warning alert-dismissible circular">
                    <h5><i class="icon mdi mdi-alert-decagram-outline"></i>Cuidado!</h5>
                    Estas seguro de eliminar el registro <b>{{ object }}</b>?
                </div>
            </div>
            <div class="card-footer circular-bottom">
                <button type="submit" class="btn btn-danger circular">
                    <i class="mdi mdi-content-save"></i> Si, aceptar
                </button>
                <a href="{{ list_url }}" class="btn btn-primary circular">
                    <i class="mdi mdi-cancel"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
{% comment %}      $('form').on('submit', function (e) {
        e.preventDefault();
        let parameters = new FormData(this);
        submit_with_ajax(window.location.pathname, 'Notificacion',
          'Estas seguro de eliminar el siguiente registro?', parameters, () => {
            Swal.fire({
              title: 'Alerta',
              html: 'Registro eliminado correcta mente',
              icon: 'success',
              timer: 2000,
              onClose: () => {
                location.href = '{{ list_url }}'
              }
            })
          })
      });{% endcomment %}
    </script>

{% endblock %}

templates/footer.html
{% load static %}
<!-- Main Footer -->
<footer class="main-footer p-2 text-center user-select-none">
    <strong>Copyright &copy; <span id="year"></span> <a href="#">Techno$TΛЯ™</a></strong><br>
    All rights reserved.
</footer>
<script>
  if (new Date().getFullYear() === 2021)
    document.getElementById('year').innerHTML = `2021`
  else
    document.getElementById('year').innerHTML = `2021-${new Date().getFullYear()}`
</script>

templates/form.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block head %}
    {% block head_form %}

    {% endblock %}
{% endblock %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="card card-info circular">
            <div class="card-header circular-top">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="mdi mdi-plus"></i>
                    {% else %}
                        <i class="mdi mdi-square-edit-outline"></i>
                    {% endif %}

                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}

                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger circular alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                        <h5><i class="icon mdi mdi-content-save-settings"></i>Ha ocurrido un error al querer guardar el
                            registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}
                    <div class="form-group row">
                        <label for="asd" class="col-sm-2 col-form-label">{{ field.label }}:</label>
                        <div class="col-sm-10">
                            {{ field|add_class:'form-control circular'|attr:'autocomplete:off' }}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer circular-bottom">
                <button type="submit" class="btn bg-gradient-primary circular">
                    <i class="mdi mdi-content-save"></i> Guardar {{ entity }}
                </button>
                <a href="{{ list_url }}" class="btn bg-gradient-danger circular">
                    <i class="mdi mdi-cancel"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
      {% if form.errors %}
        let errors = '';
        {% for field in form %}
          {% for error in field.errors %}
            errors += '{{ error }}\n';
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          errors += '{{ error }}\n';
        {% endfor %}

        Swal.fire({
          title: 'Error',
          text: errors,
          icon: 'error'
        });
      {% endif %}

      {% comment %}      $('form').on('submit', function (e) {
              e.preventDefault();
              let parameters = new FormData(this)
              submit_with_ajax_alert(window.location.pathname, 'Notification', 'Are you sure?', parameters, () =>
                location.href = '{{ list_url }}', 'mdi mdi-cancel')
            }){% endcomment %}
    </script>
{% endblock %}

templates/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary" id="header">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="mdi mdi-menu mdi-18px"></i></a>
        </li>
{% comment %}        <li>
            <a class="nav-link pl-0 cursor-pointer" data-toggle="modal" data-target="#links"
               role="button">
                <i class="mdi mdi-link-variant mdi-18px"></i></a>
        </li>{% endcomment %}
        <li class="nav-item">
            <a href="#" class="nav-link pl-0"><i
                    class="mdi mdi-home d-sm-inline-block pl-0 pr-0"></i>
                <span class=" d-none d-sm-inline-block"> Inicio</span>
            </a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <a href="#"></a>
        {% if request.user.groups.all %}
            <li class="nav-item dropdown show">
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
                   class="nav-link{% if request.user.groups.all.count > 1 %}
                       {% endif %}  dropdown-toggle">{{ request.session.group }}</a>

                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0; right: inherit;min-width: auto">
                        {% for g in request.user.groups.all %}
                            {% if g.id != request.session.group.id %}
                                <li><a href="{% url 'user:user_change_group' g.id %}"
                                       class="dropdown-item circular">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}

        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="mdi mdi-account-settings mdi-18px"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header truncate-1" style="font-size: 12px;">
                       You last login was {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
{#                <a href="{% url 'user:user_update' request.user.id %}" class="dropdown-item">#}
                <a href="#!" class="dropdown-item">
                    <i class="mdi mdi-account-edit mdi-18px mr-2"></i> Edit profile
                    <span class="float-right text-muted text-sm"></span>
                </a>
                <div class="dropdown-divider"></div>
{#                <a href="{% url 'user:user_change_password' %}" class="dropdown-item">#}
                <a href="#" class="dropdown-item">
                    <i class="mdi mdi-lock mdi-18px mr-2"></i> Edit password
                    <span class="float-right text-muted text-sm"></span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer circular-bottom">
                    <p>bla bla bla bla bla</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="mdi mdi-power" style="font-size: 20px" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/login.html
{% load static %}

<!DOCTYPE html>
<html class=''>
<head>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"
          id="bootstrap-css">
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src='https://production-assets.codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js'></script>
    <script src='//production-assets.codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js'></script>
    <script src='//production-assets.codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js'></script>
    <meta charset='UTF-8'>
    <meta name="robots" content="noindex">
    <link rel="shortcut icon" type="image/x-icon"
          href="//production-assets.codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico"/>
    <link rel="mask-icon" type=""
          href="//production-assets.codepen.io/assets/favicon/logo-pin-f2d2b6d2c61838f7e76325261b7195c27224080bc099486ddd6dccb469b8e8e6.svg"
          color="#111"/>
    <link rel="canonical"
          href="https://codepen.io/aperyon/pen/oxzpaE?depth=everything&order=popularity&page=23&q=translate&show_forks=false"/>

    <style class="cp-pen-styles">html, body {
        border: 0;
        padding: 0;
        margin: 0;
        height: 100%;
    }

    body {
        background: tomato;
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 16px;
    }

    form {
        background: white;
        width: 40%;
        box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.7);
        font-family: lato;
        position: relative;
        color: #333;
        border-radius: 10px;
    }

    form header {
        background: #FF3838;
        padding: 30px 20px;
        color: white;
        font-size: 1.2em;
        font-weight: 600;
        border-radius: 10px 10px 0 0;
    }

    form label {
        margin-left: 20px;
        display: inline-block;
        margin-top: 30px;
        margin-bottom: 5px;
        position: relative;
    }

    form label span {
        color: #FF3838;
        font-size: 2em;
        position: absolute;
        left: 2.3em;
        top: -10px;
    }

    form input {
        display: block;
        width: 78%;
        margin-left: 20px;
        padding: 5px 20px;
        font-size: 1em;
        border-radius: 3px;
        outline: none;
        border: 1px solid #ccc;
    }

    form .help {
        margin-left: 20px;
        font-size: 0.8em;
        color: #777;
    }

    form button {
        position: relative;
        margin-top: 30px;
        margin-bottom: 30px;
        left: 50%;
        transform: translate(-50%, 0);
        font-family: inherit;
        color: white;
        background: #FF3838;
        outline: none;
        border: none;
        padding: 5px 15px;
        font-size: 1.3em;
        font-weight: 400;
        border-radius: 3px;
        box-shadow: 0px 0px 10px rgba(51, 51, 51, 0.4);
        cursor: pointer;
        transition: all 0.15s ease-in-out;
    }

    form button:hover {
        background: #ff5252;
    }
    </style>
</head>

<body>

<form method="post" action="/login/">
    {% csrf_token %}

    <header>Login</header>
    <label>Username <span>*</span></label>
    <input type="text" name="username" placeholder="Username" required=""/>
    <div class="help">At least 5 character</div>
    <label>Password <span>*</span></label>
    <input type="password" name="password" placeholder="Password" required=""/>
    <div class="help">Use upper and lowercase letters as well</div>
    <button type="submit" >Enviar</button>

</form>

</body>
</html>

templates/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="#" class="brand-link">
        <img src="{% static 'img/balita.png' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Gestión del gas UCI</span>
    </a>
    <div class="sidebar">
        <div class="user-panel py-2  d-flex">
            <div class="image">
                <img src="{% if request.user.get_image %}{{ request.user.get_image }}
                            {% else %}{% static 'img/user2.png' %}{% endif %}"
                     class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="{% url 'index' %}" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>
        <div class="rayita-light"></div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Informes</li>
                {% if request.user.role == 'client' or request.user.is_superuser %}
                    <li class="nav-item">
                        <a href="{% url 'balita:incidencia_list' %}" class="nav-link incidencia-sidebar">
                            <i class="nav-icon mdi mdi-file-question "></i>
                            <p>
                                Incidencias
                            </p>
                        </a>
                    </li>
                {% endif %}
                {% if request.user.role == 'admin' or request.user.is_superuser %}
                    <li class="nav-item">
                        <a href="{% url 'balita:venta_list' %}" class="nav-link venta-sidebar">
                            <i class="nav-icon mdi mdi-cart"></i>
                            <p>
                                Ventas
                            </p>
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a href="{% url 'balita:reserva_list' %}" class="nav-link reserva-sidebar">
                        <i class="nav-icon mdi mdi-checkbox-multiple-marked"></i>
                        <p>
                            Reservaciones
                        </p>
                    </a>
                </li>
{#                <li class="nav-item">#}
{#                    <a href="#" class="nav-link reserva-sidebar">#}
{#                        <i class="nav-icon mdi mdi-checkbox-multiple-marked"></i>#}
{#                        <p>#}
{#                            Entrega#}
{#                        </p>#}
{#                    </a>#}
{#                </li>#}
                <div class="rayita-light"></div>
                <li class="nav-header">Contrataciones</li>
                {% if request.user.role == 'admin' or request.user.is_superuser %}
                    <li class="nav-item">
                        <a href="{% url 'balita:contrato_list' %}" class="nav-link contrato-sidebar">
                            <i class="nav-icon mdi mdi-file-document"></i>
                            <p>
                                Contratos
                            </p>
                        </a>
                    </li>
                {% endif %}
                {% if request.user.role == 'admin' or request.user.is_superuser %}
                    <li class="nav-item">
                        <a href="{% url 'user:user_list' %}" class="nav-link user-sidebar">
                            <i class="nav-icon mdi mdi-account-group"></i>
                            <p>
                                Usuarios
                            </p>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</aside>

templates/startpage.html
{% extends 'body.html' %}
{% load static widget_tweaks %}
{% block head %}

{% endblock %}
{% block content %}
    <h2>Start page</h2>
{% endblock %}